# Use cibuildwheel v2 to build wheels for Python 3.
# Based on https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels2

on: workflow_dispatch

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

#   - name: checkout monomers
#     uses: actions/checkout@v3
#     with:
#       repository: MRC-LMB-ComputationalStructuralBiology/monomers
#       path: monomers

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BUILD: 'cp*'
        CIBW_SKIP: 'cp36-* *musllinux* *_i686 *-win32'
        CIBW_ARCHS_MACOS: x86_64 arm64
        #CIBW_ENVIRONMENT: CLIBD_MON=/host/${{runner.workspace}}/servalcat/monomers


    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: wheels2
        path: wheelhouse/*.whl
